#Feature-54 Add contact entity, dto, mapper, repository and service
alkemyTech/OT298-server pull request #10
Opened 2022-09-17 01:00 UTC by andyholes

2022-09-17 20:47 UTC, turcoamado requested changes
Hiciste de mas, no hacia falta codificar los metodos CRUD del service, pero estan bien, no los borres.

Un detalle, saliste del mismo branch donde trabajaste con el modelo de User, eso no deberia haber sido asi, sino que tendrias que haber creado un branch nuevo a partir de develop, vos lo creaste a partir del otro.

Entonces, primero dale bola a las modificaciones del otro branch, terminamos prolijo ese, hacemos un pull de develop y te actualizas este para luego continuar trabajando aca. Cualquier cosa si no entendes preguntame

2022-09-17 20:47 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/ContactDTO.java
> +    @Pattern(regexp = "^[A-Za-z]*$")
Me gusta que hayas utilizado expresiones regulares para la validacion.

2022-09-17 20:47 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Contact.java
> +    @NotBlank
Me gusta que hayas utilizado expresiones regulares para la validacion.
Lo que faltaria seria el mensaje de error en caso de ser nulo, para este y los demas casos donde no pueden serlo

2022-09-17 20:47 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Contact.java
> +    private Timestamp deletedAt;
yo le pondria otro nombre, ya que si actualizo algun otro campo de la entidad tambien deberia guardarse la fecha y no es una eliminacion.
Lo que te falto es lo mismo pero para la fecha de creacion

2022-09-17 20:47 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/ContactServiceImpl.java
> +    ContactRepository contactRepository;
las variables deberian ser privadas

2022-09-20 01:35 UTC, turcoamado commented
@andyholes por que cerraste el PR? Es mas facil de lo que parece, debes seguir trabajando en la misma rama realizando los cambios, luego haces commit & push y se actualiza el PR de forma automatica, me llega la notificacion y lo veo aca mismo. No hace falta cerrarlo y abrir uno nuevo (y no es buena practica tampoco)

2022-09-20 02:07 UTC, andyholes commented
quise reemplazar la rama que habia hecho por una que surja desde develop y ya  no me dejo reabrir el PR. Abro uno nuevo? Solo hice corrección de lo que me habias indicado en los comentarios

2022-09-20 04:18 UTC, turcoamado approved these changes
joyaa

2022-09-20 07:30 UTC, merged