#Feature-51 Add activities endpoint
alkemyTech/OT298-server pull request #17
Opened 2022-09-20 09:52 UTC by andyholes

- Activity Controller, Service, DTO and Mapper implementation
- RequestBody validation and validationHandler implementation
- pom.xml changes (Hibernate Validation dependency added)

2022-09-21 16:42 UTC, turcoamado requested changes
Andres esta muy bien! Te marque algunos detalles nada mas. Ojo con el pom, creo que te esta faltando actualizarte develop, porque me figura que estas eliminando dos dependencias

2022-09-21 16:42 UTC, turcoamado commented on pom.xml
> -			<groupId>org.hibernate.validator</groupId>
Ojo que me figura como que estas eliminando dos dependencias del pom, la de validator y la de sendgrid

2022-09-21 16:42 UTC, turcoamado commented on src/main/java/com/alkemy/ong/rest/ActivityController.java
> +    private ActivityServiceImpl activityService;
aca se deberia inyectar la interface del servicio en lugar de la implementacion

2022-09-21 16:42 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/ActivityServiceImpl.java
> +        Activity activity = activityMapper.activityDTOToActivity(dto);
Se podria encerrar todo lo que esta en este metodo en un bloque try catch para manejar algun error inesperado del server, ese seria con error 500. Raro que suceda pero seria atajar por ejemplo algun bardo que suceda justo en el momento de la persitencia, ponele se te cae el servidor o la DB

2022-09-21 23:11 UTC, andyholes commented on pom.xml
> -			<groupId>org.hibernate.validator</groupId>
ahora me hago un pull de develop y trato de resolver los conflictos esos antes de pushear

una consulta: si usamos spring-boot-starter-validation hace falta tener el hibernate-validator? porque yo estaba usando solo el primero por eso sacaba el segundo

2022-09-21 23:12 UTC, andyholes commented on src/main/java/com/alkemy/ong/service/impl/ActivityServiceImpl.java
> +        Activity activity = activityMapper.activityDTOToActivity(dto);
perfecto! Ya lo agrego

2022-09-22 16:16 UTC, turcoamado commented on pom.xml
> -			<groupId>org.hibernate.validator</groupId>
El Hibernate validator es para las annotations de las entities, es lo que te permite poner el @NotNull por ejemplo

2022-09-23 16:27 UTC, turcoamado approved these changes
Bueno la logica del endpoint esta genial! Lo unico que veo es que estas teniendo quilombos con el pom, ahora aparece como que estas eliminando la dependencia que se utiliza para sendgrid.
Yo te lo dejo como aprobado, pero porfa chequeate bien eso, mira te dejo aca abajo el pom que esta actualmente en develop (aunque lo podrias ver si entras al codigo tambien)

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.1</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.alkemy</groupId>
	<artifactId>ong</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>ong</name>
	<description>ONG project with Spring Boot</description>
	<properties>
		<java.version>11</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.session</groupId>
			<artifactId>spring-session-core</artifactId>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt</artifactId>
			<version>0.9.1</version>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>1.4.2.Final</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.sendgrid</groupId>
			<artifactId>sendgrid-java</artifactId>
			<version>4.4.1</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>1.4.2.Final</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>0.2.0</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
```

2022-09-23 16:27 UTC, turcoamado commented on pom.xml
> -			<groupId>com.sendgrid</groupId>
Cuidado! Figura como que estas eliminando la dependencia de sendgrid

2022-09-23 17:50 UTC, andyholes commented on pom.xml
> -			<groupId>com.sendgrid</groupId>
Ahora acomodo mi pom para que coincida con el de develop 👍

2022-09-23 18:43 UTC, merged