OT29825 feat: add endpoint user registration
alkemyTech/OT298-server pull request #18
Opened 2022-09-20 18:58 UTC by CarolinaCQ

2022-09-21 18:31 UTC, turcoamado requested changes
Muy bueno lo trabajado aca! Lo unico, veo que manejaste excepciones y vi algo de esto en un PR de otro de los chicos, van a tener que ponerse de acuerdo para ver en que lugar lo meten y con que nombre, para no crear cosas duplicadas

2022-09-21 18:31 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/User.java
> -    @Pattern(regexp = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–{}:;',?/*~$^+=<>]).{8,20}$")
esta la sacaste porque la pusiste en el dto del request?

2022-09-21 18:31 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> +                    "There is an account with that email adress:" + dto.getEmail(), HttpStatus.BAD_REQUEST);
Este mensaje  (y todos los de error que se envien hacia el cliente) podrian estar en un handler de mensajes y escribirse en un archivo properties definido para ese fin. Esto es por varias razones, al menos tenemos dos, una es que no es buena practica tener nada de forma hardcoded entonces intentaremos evitar eso lo mas posible. La otra te la ejemplifico de la siguiente manera, pensemos que estamos desarrollando una app multilenguaje, entonces va a ser una version si esta en esp y otra si esta en eng, imaginate que no podemos codificar dos aplicaciones diferentes unicamente porque necesitamos que el mensaje de error sea en dos idiomas distintos, entonces se pone en un properties y luego se ejecutara uno u otro segun la compilacion. Nosotros no vamos a llegar a tanto pero esta bueno que tengan el concepto.
No hace falta que lo modifiques ahora porque hay que implementar algo, pero se los voy a pasar por el chat para que a partir del proximo sprint se implemente y luego los mensajes se pasen de esa manera, mientras te dejo unos links de una implementacion como para que vayas chusmeando si queres
https://looksok.wordpress.com/tag/message-properties/
https://zetcode.com/spring/messagesource/

2022-09-22 00:36 UTC, andyholes commented on src/main/java/com/alkemy/ong/model/User.java
> -    @Pattern(regexp = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–{}:;',?/*~$^+=<>]).{8,20}$")
hola! me meto a la conversación jajaja
yo había hecho la entidad user y con caro hablando nos dimos cuenta que ese regex limitaba los caracteres entre 8 y 20 entonces le daba error al querer guardar la password hasheada, por eso el regex quedo solo en el dto

2022-09-22 13:45 UTC, CarolinaCQ commented on src/main/java/com/alkemy/ong/model/User.java
> -    @Pattern(regexp = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–{}:;',?/*~$^+=<>]).{8,20}$")
Sii, justo le explique eso ayer al Turco

2022-09-22 16:14 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/User.java
> -    @Pattern(regexp = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–{}:;',?/*~$^+=<>]).{8,20}$")
Perfecto chicos

2022-09-22 16:15 UTC, turcoamado approved these changes
Lo dejo aprobado, tengan en cuenta antes de hacer el merge lo que les mencione de las excepciones

2022-09-23 02:33 UTC, merged