OT29816 feat: Add organization model and organization repository
alkemyTech/OT298-server pull request #2
Opened 2022-09-15 16:31 UTC by CarolinaCQ

2022-09-16 20:33 UTC, turcoamado requested changes
Esta muy bien que hayas utilizado las annotations para las validaciones! Lo que haria diferente seria elegir el nombre de los atributos, no le pondria a todo organization por delante.

Me parecio raro que hayas utilizado el yml para configurar la DB, por lo general es el application.properties, tampoco esta mal  hasta donde se.
Lo que si no esta bueno es que este subido el archivo, raro porque veo que lo pusiste en el gitignore, pero lo esta subiendo igual. Lo que podrias hacer para esto es sacarlo del commit o subirlo en blanco y siempre tener cuidado al pushear

2022-09-16 20:33 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Organization.java
> +    private LocalDateTime updateDate;
Faltaria agregar la annotation @CreationTimestamp.

2022-09-16 20:33 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Organization.java
> +    private LocalDateTime removalDate;
Este quizas lo llamaria diferente, y lo utilizaria para cualquier tipo de actualizacion. Se puede poner con la annotation @UpdateTimestamp

2022-09-16 20:39 UTC, turcoamado requested changes

2022-09-16 20:39 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Organization.java
> +    private Boolean deleted;
Te estan faltando las queries que hay que utilizar para que el soft delete sea efectivo

2022-09-20 00:45 UTC, turcoamado approved these changes
buenisimo!

2022-09-20 00:45 UTC, turcoamado commented on .gitignore
> -application.yml
estas usando el application.properties ahora?

2022-09-20 00:54 UTC, CarolinaCQ commented on .gitignore
> -application.yml
Sisi estoy usando application.properties

2022-09-20 01:00 UTC, merged