Feature ot298 24 organization public info endpoint
alkemyTech/OT298-server pull request #20
Opened 2022-09-21 18:10 UTC by joeldevel

Por lo que entiendo del proyecto, solamente hay una organización. Por eso es que entiendo que en la tabla de organizations solamente hay un registro. Es por eso que definí en el repositorio de Organization un método que trae el último registro.

2022-09-21 19:48 UTC, turcoamado requested changes
Esta bien lo que asumiste, vamos a manejarnos con una sola organization

2022-09-21 19:48 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/OrganizationBasicDTO.java
> +    public OrganizationBasicDTO(String name, Integer phone, String address, String image) {
Para evitar la creacion del constructor tambien se pueden utilizar annotations de Lombok

2022-09-21 19:48 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        Organization organization = organizationRepository.findFirstByOrderByCreationDateDesc();
Le agregaria un bloque try catch por si por alguna razon llegase a fallar algo del servidor, ese seria un error 500 ya que estariamos agarrando una explosion del server que no tenemos idea de por que sucedio

2022-09-23 19:56 UTC, joeldevel commented
Con el tema del try-catch en el servicio, no se añadió porque hemos decidido usar ControllerAdvice y manejar ese tipo de errores con el método handleGlobalException.

2022-09-23 20:21 UTC, turcoamado approved these changes
buenisimo

2022-09-23 20:28 UTC, merged