#Feature-53 Add ActivityDataLoader seed
alkemyTech/OT298-server pull request #27
Opened 2022-09-26 22:27 UTC by andyholes

2022-09-26 22:29 UTC, andyholes commented
Lo subi mal

2022-09-27 00:00 UTC, andyholes commented
Por confusión puse la rama "main" como destino del PR.
Ya lo cambie a "develop"

2022-09-27 17:29 UTC, turcoamado requested changes

2022-09-27 17:29 UTC, turcoamado commented on src/main/java/com/alkemy/ong/util/ActivityDataLoader.java
> +    private ActivityRepository activityRepository;
Seria mejor inyectarle el service, entonces podrias hacer un getAll() por ejemplo y fijarte si hay o no registros para de esa manera no romper la division de capas, entonces pasamos siempre por el service para poder llegar al repository

2022-09-28 13:51 UTC, turcoamado approved these changes

2022-09-28 13:51 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/ActivityServiceImpl.java
> +        for (Activity activity : activityList){
Solo para que lo sepas nada mas, esto se podría haber resuelto con una expresión lambda, pero no hace falta que modifiques nada, es para que tengas otra opción. Quedaría algo como:
```
activityList.forEach{ activity -> 
      ActivityDTO dto = activityMapper.activityToActivityDTO(activity);
      dtoList.add(dto);
}
```
Esta es una de las opciones, hay mas y quizás optimizando mejor, lo que te puse yo es simplemente como hacer un for each con una expresión lambda, lo mismo que hiciste vos con el for each tradicional

2022-09-28 21:38 UTC, merged