OT29873 feat: add users test data and fix message
alkemyTech/OT298-server pull request #29
Opened 2022-09-27 02:02 UTC by CarolinaCQ

2022-09-27 17:35 UTC, turcoamado requested changes
Bien Caro! (o Cami, recordame como es que te llaman). Lo unico que cambiaria seria poner nombres que simulen ser reales, siempre es mejor probar las cosas con casos lo mas reales posibles, y para una demo por ejemplo es una mejor practica.

2022-09-27 17:35 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +                    message.getMessage("email.exists", null, Locale.US));
Buenisimo!

2022-09-27 18:44 UTC, CarolinaCQ commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +                    message.getMessage("email.exists", null, Locale.US));
Caro esta bien 😊 perfecto ahora modifico los nombres para que simulen ser mas reales

2022-09-28 19:53 UTC, CarolinaCQ commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +                    message.getMessage("email.exists", null, Locale.US));
![bad_request_email_exists](https://user-images.githubusercontent.com/92055917/192875832-26035d05-ab66-44ec-ba6c-f34c3a6ddf47.PNG)
Turco te dejo la captura de esta excepción

2022-09-29 13:50 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +                    message.getMessage("email.exists", null, Locale.US));
Buenisimo Caro! Muchas gracias

2022-09-29 13:50 UTC, turcoamado approved these changes

2022-09-29 14:14 UTC, merged