#Feature-43 Add category controller and service
alkemyTech/OT298-server pull request #32
Opened 2022-09-27 14:50 UTC by andyholes

- Add save method in CategoryController accesible only by admin
- Add annotation AllowedRoles("ADMIN") in ActivityController
- Add handleHttpMessageNotReadable method in ControllerExceptionHandler

2022-09-27 18:19 UTC, turcoamado requested changes
Muy bueno el PR, unicamente te comente lo de los roles

2022-09-27 18:19 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    @RolesAllowed("ADMIN")
Esto es valido, pero mejor si lo ponemos dentro del archivo de configuracion de JWT con un `.antMatchers()`
Conviene de esa manera para tenerlo todo centralizado y facilita muchas veces luego el testing.
Lo que hay que tener en cuenta es que manejen el rol con ese nombre, eso lo tienen que decidir entre ustedes

2022-09-27 18:19 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    @RolesAllowed("ADMIN")
Lo mismo que te comente en ActivityController

2022-09-27 18:19 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Category.java
> +    @NotNull(message = "{request.name}")
Buenisimo el cambio

2022-09-27 18:19 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Category.java
> +    @Pattern(regexp = "^[A-Za-z]*$", message = "{request.letters}")
Barbara la validacion!

2022-09-27 18:54 UTC, andyholes commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    @RolesAllowed("ADMIN")
Perfecto! Ya lo acomodo

2022-09-27 19:14 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    @RolesAllowed("ADMIN")
Ahi vi los cambios, recorda agregarlo en donde tienen la configuracion de seguridad que segun vi es la clase **AppSecurity**. Al menos dejalo de forma comentada y cuando definan los roles se acomoda, podes fijarte el PR de Cristian que hizo eso (https://github.com/alkemyTech/OT298-server/pull/28)

2022-09-28 14:03 UTC, turcoamado approved these changes
Lo dejo aprobado, unicamente hay que tener en cuenta cuando este definido el tema de roles acomodar el **AppSecurity** para cumplir lo requerido

2022-09-28 14:03 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    //TODO: @RolesAllowed("ADMIN")
Recorda que esto en ralidad deberia ir en la clase **AppSecurity**

2022-09-28 14:03 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    //TODO: @RolesAllowed("ADMIN")
Recorda que esto en ralidad deberia ir en la clase **AppSecurity**

2022-09-28 21:39 UTC, merged