Feature OT298-50
alkemyTech/OT298-server pull request #33
Opened 2022-09-27 14:50 UTC by laudebor

**Summary**

- Modified user registration method to return token
- Jwt filter added

2022-09-27 17:55 UTC, turcoamado requested changes

2022-09-27 17:55 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/filter/JwtRequestFilter.java
> +    public static final String AUTHORIZATION = "Authorization";
Me gusta que hayas puesto estas dos como variables estaticas de clase. Lo unico, hacelas privadas, porque no creo que se tengan que utilizar por fuera, en todo caso se haran publicas llegado el momento

2022-09-27 17:55 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +        return new AuthResponse(jwt);
El objeto AuthResponse unicamente tiene el string jwt, entonces ahora cuando se registra como cambiaste la respuesta se esta devolviendo SOLAMENTE el token y perdimos los datos del usuario y estamos rompiendo lo requerido por el ticket que tenia ese feature (https://alkemy-labs.atlassian.net/browse/OT298-25).
Lo que planteaste esta casi perfecto, unicamente que lo que debias hacer era de alguna manera modificar alguno de los DTOs o crear uno nuevo, para que tenga ambas cosas: los datos del usuario (que estaban en el DTO original que se utilizaba en el endpoint, y el token que esta en este AuthResponse

2022-09-27 22:03 UTC, laudebor commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +        return new AuthResponse(jwt);
Ahh bien, entiendo! Perfecto, entonces voy a agregarle el atributo que contenga el jwt al userGetDTO que teníamos antes. Gracias Turco!

2022-09-28 14:05 UTC, turcoamado approved these changes
Bárbaro! Ahora si

2022-09-28 14:14 UTC, laudebor commented
> 

Genial, gracias!!

2022-09-28 18:43 UTC, merged