OT29841 feat: add category list endpoint
alkemyTech/OT298-server pull request #34
Opened 2022-09-27 18:39 UTC by CarolinaCQ

2022-09-27 19:26 UTC, turcoamado requested changes

2022-09-27 19:26 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        return listDtosCategories;
Faltaria agregar un mensaje si el listado esta vacio, para que quede mas lindo en lugar de mostrar un json vacio entonces mostrariamos un mensaje indicando que no hay categorias. En este caso no es un error entonces no cambiaria el codigo http, o en todo caso se podria enviar un NO_CONTENT

2022-09-27 19:45 UTC, CarolinaCQ commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        return listDtosCategories;
Perfecto lo agrego!

2022-09-28 20:56 UTC, CarolinaCQ commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        return listDtosCategories;
![array_is_empty](https://user-images.githubusercontent.com/92055917/192886907-982f6414-7f69-49af-b4cc-63e6836531a9.PNG)
@turcoamado

2022-09-29 13:52 UTC, turcoamado approved these changes
Te lo dejo como aprobado pero modificale el tipo de exception y el mensaje y luego mergealo. Muy bien Caro

2022-09-29 13:52 UTC, turcoamado commented on src/main/resources/messages.properties
> +array.isEmpty="The array is empty"
Bien, pero en lugar de ponerle que el array esta vacío ponele que no hay categorías o algo así, porque un usuario en realidad no sabe que es un array, pero esta bien! Esto es lo que decía de hacer

2022-09-29 14:15 UTC, CarolinaCQ commented on src/main/resources/messages.properties
> +array.isEmpty="The array is empty"
Perfecto lo modifico! Graciass

2022-09-29 14:59 UTC, merged