EndPoint-addcoments-OT298-77
alkemyTech/OT298-server pull request #35
Opened 2022-09-28 11:18 UTC by GastonGarcia97

Tested and working

2022-09-28 14:40 UTC, turcoamado requested changes
Está bien planteado pero te dejé algunas observaciones con respecto a los errores. Y de paso te consulto, cuando te falla, qué códigos de error se están generando?

2022-09-28 14:40 UTC, turcoamado commented on .gitignore
> +pom.xml
por qué estas agregando todo esto al gitignore? 
El pom se podría modificar cada vez que se agregue una dependencia necesaria, por ejemplo las que se tuvieron que agregar para las validaciones, o las libreriías de amazon o sendgrid.
No entiendo tampoco el agregado de la clase SendGridEmailService

2022-09-28 14:40 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> +            if(commentEntity==null) {
Entiendo el punto, pero dos cosas, primero que no esta bueno mandar un error así al usuario, porque no sabe que es un DTO, entonces si el error le dice "El DTO es null" no va a entender que está pasando. Por otro lado, el DTO que llega nunca va a ser null, porque es el del request y se está validando que vengan los datos correspondientes con la annotation @Valid del controller más las annotations que le pusiste al DTO

2022-09-28 14:40 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> +                throw new ParameterNotFound(messageSource.getMessage("not.saved.entity",null,Locale.US));
Este error no lo entiendo tampoco, por lo que veo es que está fallando el guardado y está bien que se catchee eso, pero me parece que no corresponde a un ParameterNotFound, el error es otro. Y el mensaje tampoco debería ser entidad no guardada, porque tampoco sabe el usuario que es una entidad, siempre hay que fijarse de que debe entender lo que estamos diciéndole, entonces yo podría algo como "Error al intentar guardar el comentario" por ejemplo, puede ser otra cosa, pero que sea descriptiva

2022-09-28 14:40 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> +            throw new ParameterNotFound(messageSource.getMessage("mapper.error",null,Locale.US));
Y para este error similar, esta bien que intentes tener en cuenta todos los posibles escenarios dónde puede explotar, pero tiene que tener sentido para el usuario final además que para los desarrolladores. Entonces podría estar todo lo que haces dentro de un try catch y el error debería ser genérico al método, y decir algo como lo que te puse antes, error al guardar

2022-09-28 15:18 UTC, GastonGarcia97 commented on .gitignore
> +pom.xml
Si ,se me escapo ! ya lo arregle

2022-09-28 15:20 UTC, GastonGarcia97 commented
Me tira Bad Request con los mensaje de las anotaciones ,voy a hacer incapie en los https status que tiran y de no mandar tantas excepciones por linea jaja 
gracias por las correcciones!

2022-09-29 13:48 UTC, turcoamado requested changes

2022-09-29 13:48 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Comment.java
> +    private Long userId;
No me había dado cuenta de esto! No corresponde, ya tenemos el User en el atributo anterior y allí mismo se realiza el mapeo, no es necesario declarar otro atributo que sea el id. Lo mismo para news y todas aquellas clases que se relacionen con una FK, para el código java funciona matcheando entidades, en la DB se guarda el id justamente con el name user_id que está definido en @JoinColumn.  

Así que porfa sacate el userId y lo mismo para el newsId

2022-09-29 13:48 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> +                throw new ParameterNotFound(messageSource.getMessage("not.saved.entity",null,Locale.US));
Te faltó modificar el mensaje del not.saved.entity y el tipo de exception

2022-10-01 08:44 UTC, closed without merging