Feature ot298 58
alkemyTech/OT298-server pull request #36
Opened 2022-09-29 07:45 UTC by Alejandro-Toloza

No estoy entendiendo bien la segunda consigna respecto a s3. 

* Se debe hacer una peticion POST /Slides 
* Recibirá la imágen a almacenar en base 64. La misma deberá ser decodeada y almacenada en Amazon S3. 
* En el caso de no recibir el campo order, deberá establecer el mismo como el último en base a los existentes

Lo pensé suponiendo que la imagen la recibo ya en base64.
Entonces realizo el decode de imageString, después la paso a un archivo decodeImg y por ultimo cuando llamo al método que implementó uno de los compañeros debo parsear ese archivo a MultipartFile para que me lo tome. No pude probar el código por que no estoy seguro de si entendí la consigna o me enredé solo. El código compila sin errores pero nose si realmente se llega a guardar en el bucket.

2022-09-29 15:22 UTC, turcoamado requested changes
Ojo que me figura como que estás eliminando el NewsController, fijate de actualizar tu branch con lo último que está en develop.

Con respecto al método para guardar, en rasgos generales se ve bien, pero te está faltando cumplir con esta condición: 
> En el caso de no recibir el campo order, deberá establecer el mismo como el último en base a los existentes

El campo order ustedes lo guardaron como _orders_ que yo lo modificaría y le pondria _position_, u _order_ (en singular), el tema es que _order_ en singular no pueden utilizar en la DB porque es una palabra reservada, pero se puede renombrar con la annotation @Column.

Te está faltando la parte de almacenar la ruta en la que efectivamente se estaría guardando la imagen, con esa ruta podes verla si la pegas en un navegador

2022-09-29 15:22 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/SlidesServiceImpl.java
> +    SlidesRepository slidesRepository;
estas variables hacelas privadas

2022-09-29 15:22 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/SlidesServiceImpl.java
> +        mediaStoreService.uploadFile((MultipartFile) file);
Esto te esta devolviendo un **MediaBasicDTO**, dentro de ese DTO tenés la url a la imagen, esa url es la que tenés que guardar en la entity Slide, sino tu slide se guarda sin la referencia a la imagen en si que se estaría almacenando en al bucket de amazon

2022-09-29 15:23 UTC, turcoamado commented
Estaría bueno que charlen un poco entre ustedes para ver como realizar todo el feature de la mejor manera posible, ya que convergen varios tickets acá (desde la creación del modelo Slide, la configuración de AWS, el servicio reutilizable para subir imágenes y la carga que es lo que estás realizando vos)

2022-09-29 21:53 UTC, turcoamado requested changes
te comenté un poco más sobre la url y lo que hablamos del orden por discord

2022-09-29 21:53 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/SlidesServiceImpl.java
> +        slides.setImage(mediaBasicDTO.getUrl());
va mejor, pero sigue estando incompleto, porque que objeto es mediaBasicDTO? Es el que obtenés de la línea 41, entonces deberías hacer:
`mediaBasicDTO = amazonS3Service.uploadFile((MultipartFile) file);`

2022-09-29 22:10 UTC, Alejandro-Toloza commented on src/main/java/com/alkemy/ong/service/impl/SlidesServiceImpl.java
> +        slides.setImage(mediaBasicDTO.getUrl());
Sii, me faltó subir esa corrección me di cuenta después, lo que si estoy todavía viendo el tema del order que no me queda muy claro. Pero ahora estoy tratando de implementar un método y lo subo.

2022-10-03 16:29 UTC, turcoamado approved these changes

2022-10-04 03:08 UTC, merged