Feature ot298 36 get user list endpoint
alkemyTech/OT298-server pull request #39
Opened 2022-09-30 13:22 UTC by montexbjeliseo

**Summary**
- UserController: /users with get method
- AuxDto for User
- Critical Security Errors fixed

**Evidence**
Access Denied to User
![getUsers403](https://user-images.githubusercontent.com/106119225/193278886-09e82740-cf56-4e8f-99c7-83012665bd3c.PNG)
Access Grandted to Admin
![getUsers200](https://user-images.githubusercontent.com/106119225/193278891-eb723059-8ec9-4956-bdad-cb9853cf8886.PNG)

2022-09-30 21:20 UTC, turcoamado requested changes
No miré nada de lo referido a Categories porque era bastante y no entiendo la razón por la cual lo tenés acá.
Si te hice algunas observaciones con lo otro

2022-09-30 21:20 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    public ResponseEntity<CategoryCompleteGetDto> getCategoryById(@PathVariable Long id){
Por qué tenés cosas de este endpoint si tu ticket era de obtener el listado de usuarios?

2022-09-30 21:20 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/config/AppSecurity.java
> +                .antMatchers(HttpMethod.GET, "/**").hasAnyAuthority("ROLE_ADMIN", "ADMIN")
acá en realidad debes poner únicamente la ruta específica de tu endpoint, pero creeeeeo que todos los get son para ADMIN así que lo podemos dejar y después en todo caso lo evaluamos.
Lo único que si tienen que corregir es que no pueden haber dos nombres para el mismo rol, tienen que tomar uno solo, o dejan ROLE_ADMIN o dejan ADMIN

2022-09-30 21:20 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/filter/JwtRequestFilter.java
> +                //Authentication auth = authenticationManager.authenticate(authReq);
si esta línea era la que estaba mal entonces podes eliminarla directamente

2022-09-30 21:20 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/AuxUserGetDto.java
> +public class AuxUserGetDto {
El UserGetDto para qué se utiliza? En el seeder era? No queda muy entendible tener dos DTOs que se llamen tan similar, sobre todo porque este se llama Aux y sería un auxiliar de qué? Ojo, si se pueden tener diferentes eh, está perfecto eso, pero me genera un poco de confusión los nombres

2022-09-30 21:20 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +        for(User userGet : users){
Esto lo realizaste con el fin de optimizar un poco el seeder? Puede ser un arma de doble filo, porque si mañana se modifica el seeder para agregar mas usuarios rompería si queremos que el número de admins sea diferente a 10. No está mal lo que pensaste pero no se si realmente es más performante.

2022-09-30 21:20 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +        addRoleToUser("USER", savedUser);
Para evitar este hardcode USER se puede utilizar un Enum, que fue alguna de las cosas que comentamos

2022-10-01 00:15 UTC, montexbjeliseo commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    public ResponseEntity<CategoryCompleteGetDto> getCategoryById(@PathVariable Long id){
Pasa que traje la rama de Caro. Porque ella había echo unos cambios que yo necesitaba.

2022-10-01 00:17 UTC, montexbjeliseo commented on src/main/java/com/alkemy/ong/security/config/AppSecurity.java
> +                .antMatchers(HttpMethod.GET, "/**").hasAnyAuthority("ROLE_ADMIN", "ADMIN")
Eso me re olvidé de quitar. Estaba probando con ambos y resulta que el problema no era ahí. Va a quedar ROLE_ADMIN

2022-10-01 00:19 UTC, montexbjeliseo commented on src/main/java/com/alkemy/ong/dto/AuxUserGetDto.java
> +public class AuxUserGetDto {
El UserGetDto expone el jwtoken, entonces hice un auxiliar para que justamente no haga eso

2022-10-01 00:22 UTC, montexbjeliseo commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +        for(User userGet : users){
Lo del número de admins, lo traje de la rama de Caro. Voy a ver como lo solucionamos.

2022-10-01 00:24 UTC, montexbjeliseo commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +        addRoleToUser("USER", savedUser);
Vale. Lo llevaré a una clase que almacene constantes.

2022-10-03 15:52 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +        for(User userGet : users){
Está bien, ya me comentó Caro! Esto lo dejamos así, era parte del requerimiento

2022-10-03 21:24 UTC, turcoamado approved these changes
Con este PR actulizate primero con lo que haya en develop y luego eliminate la línea comentada de _JwtRequestFilter.java_ si aún está.
Después si mergea. Lo dejo como aprobado

2022-10-04 03:06 UTC, merged