Feature ot29842
alkemyTech/OT298-server pull request #40
Opened 2022-09-30 13:50 UTC by CarolinaCQ

2022-09-30 17:39 UTC, CarolinaCQ commented
@turcoamado te dejo las capturas. Graciass
![category_by_id](https://user-images.githubusercontent.com/92055917/193326125-cc11e761-f5a8-40b5-a378-cad47fee2e47.PNG)
![not_found_category_by_id](https://user-images.githubusercontent.com/92055917/193326154-c52f4731-b929-4e42-8bb2-cfec96fcf3e3.PNG)

2022-09-30 21:59 UTC, turcoamado requested changes
Lo respectivo a tu endpoint está bien, solo falta la parte de que sea accesible por el usuario administrador.
Lo otro que te mencioné supongo es de lo que sacaste del branch de Eliseo, para mi hay que modificar algunas cosas, pero deben hablarlo porque pueden surgir varios conflictos, sobre todo si lo mergeas y luego él modifica lo que tiene en curso o al revés

2022-09-30 21:59 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/filter/JwtRequestFilter.java
> +                //Authentication auth = authenticationManager.authenticate(authReq);
Si esta era la línea que estaba errónea o ahora con lo que se hizo no se necesita más se puede eliminar

2022-09-30 21:59 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +        for(User userGet : users){
Esto lo comenté en el PR de Eliseo, no me convence tanto porque si agrego más usuarios esta lógica me afecta en la asignación de roles

2022-09-30 21:59 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +        addRoleToUser("USER", savedUser);
Para evitar el hardcoded este se puede implementar el Enum que hablamos. Se lo marqué a Eliseo también

2022-09-30 22:44 UTC, CarolinaCQ commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +        for(User userGet : users){
@turcoamado Esta lógica aplique para cumplir con el ticket de seed data de usuarios, en el mismo solicitaba 10 usuarios admin y 10 regulares y este método solo se utiliza para la primera carga de los usuarios con CommandLineRunner y para el resto utiliza el register. Pero busco la forma de solucionarlo de otra forma

2022-09-30 22:45 UTC, CarolinaCQ commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +        addRoleToUser("USER", savedUser);
@turcoamado perfecto lo modificamos!

2022-09-30 22:47 UTC, CarolinaCQ commented on src/main/java/com/alkemy/ong/security/filter/JwtRequestFilter.java
> +                //Authentication auth = authenticationManager.authenticate(authReq);
Perfecto agrego lo de autorización de admin para el endpoint. Y hablo con Eliseo sobre esta linea

2022-10-03 13:54 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/service/impl/UserServiceImpl.java
> +        for(User userGet : users){
Perdón recién veo esto, si la tarjeta pedía 10 entonces está bien así!

2022-10-03 21:42 UTC, turcoamado requested changes

2022-10-03 21:42 UTC, turcoamado commented on src/main/resources/messages.properties
> +//news.notFound= News was not found with the  given id
por qué quedó comentada esta línea?

2022-10-03 21:42 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/config/AppSecurity.java
> +                .antMatchers(HttpMethod.PUT, "/news/{id}").hasAnyAuthority(ROLE_ADMIN)
Así como le sacaste las comillas a este le sacas a los demás? Así lo estandarizamos a todos. Y los que dicen ADMIN habría que ponerlos como ROLE_ADMIN

2022-10-03 21:50 UTC, CarolinaCQ commented on src/main/resources/messages.properties
> +//news.notFound= News was not found with the  given id
Dentro de develop en message.properties hay dos variables con ese mismo nombre, entonces deje comentado por ahora para hablar con el equipo y unificar los mensajes, puedo borrar una y después modificamos el mensaje nomas

2022-10-04 16:18 UTC, turcoamado commented on src/main/resources/messages.properties
> +//news.notFound= News was not found with the  given id
Ah ok perfecto! Gracias

2022-10-04 16:19 UTC, turcoamado approved these changes

2022-10-04 19:20 UTC, merged