Feature OT298-44: Endpoint Category Update
alkemyTech/OT298-server pull request #41
Opened 2022-09-30 15:35 UTC by laudebor

2022-09-30 21:36 UTC, turcoamado requested changes
Lo mismo que te marqué en el otro ticket Lau, te falta la parte de hacer que únicamente sea accesible por un usuario administrador. Lo demás está muy bien

2022-09-30 21:36 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        Optional<Category> response = categoryRepository.findById(id);
Muy bueno el uso del objeto Optional

2022-09-30 21:51 UTC, laudebor commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        Optional<Category> response = categoryRepository.findById(id);
Gracias Turco!

2022-10-03 13:47 UTC, turcoamado approved these changes

2022-10-03 14:29 UTC, merged