Feature/OT298 64
alkemyTech/OT298-server pull request #48
Opened 2022-10-03 17:07 UTC by fercuche

- Facebook, Linkedin e Instagram fields added to Organization entity.
- Update Organization DTO created.
- Organization Service updateOrganization added.

2022-10-03 21:18 UTC, turcoamado approved these changes

2022-10-03 21:28 UTC, turcoamado requested changes
Perdón, me acabo de dar cuenta que le falta agregar para que se ejecute con el usuario administador solamente

2022-10-03 21:46 UTC, fercuche commented
> Perdón, me acabo de dar cuenta que le falta agregar para que se ejecute con el usuario administador solamente

Dale! Yo no se los agregué porque Andy tenía el ticket del endpoint para actualizar los datos públicos de la organización y supuse que lo iba a agregar él.

2022-10-07 01:10 UTC, turcoamado approved these changes
joyaaaaa

2022-10-08 16:00 UTC, merged