#Feature-18 Add user entity and user repository
alkemyTech/OT298-server pull request #5
Opened 2022-09-16 02:56 UTC by andyholes

### Changelog
- User entity done
- User repository lacks of methods until a new story defines the needs of a service

2022-09-17 20:19 UTC, turcoamado requested changes

2022-09-17 20:19 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/User.java
> +    @Pattern(regexp = "^[a-zA-Z0-9]{8,16}$")
Buenisimo que hayas utilizado una RegEx!

2022-09-17 20:19 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/User.java
> +    @Column(name="first_name", nullable = false)
A este atributo y a los demas que no pueden ser nulos les falta agregar un mensaje que indique eso justamente

2022-09-17 20:19 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/User.java
> +    private Long roleId;
esta faltando la union con la tabla Role

2022-09-19 21:54 UTC, andyholes commented on src/main/java/com/alkemy/ong/model/User.java
> +    @Column(name="first_name", nullable = false)
Agregados los mensajes 👍🏻

2022-09-19 21:54 UTC, andyholes commented on src/main/java/com/alkemy/ong/model/User.java
> +    @Pattern(regexp = "^[a-zA-Z0-9]{8,16}$")
Agregados los mensajes 👍🏻

2022-09-19 21:55 UTC, andyholes commented on src/main/java/com/alkemy/ong/model/User.java
> +    @Column(name="first_name", nullable = false)
Agregados los mensajes 👍🏻

2022-09-19 21:55 UTC, andyholes commented on src/main/java/com/alkemy/ong/model/User.java
> +    private Long roleId;
Agregada la relación muchos a unos

2022-09-19 23:36 UTC, turcoamado approved these changes
joya!

2022-09-20 00:35 UTC, merged