Feature/ot298 59 update slides endpoint
alkemyTech/OT298-server pull request #66
Opened 2022-10-06 18:26 UTC by joeldevel

## update existing slides - no authorization 
![put-slides-exists-no-auth](https://user-images.githubusercontent.com/64231691/194387682-194a32c5-83d3-4def-a82c-226932296114.png)

## update existing slides - regular user 
![put-slides-exits-regular-user-forbidden](https://user-images.githubusercontent.com/64231691/194387947-51282296-956b-4cfc-9e2b-090fa3c33530.png)

## update non-existing slides - admin user - error

![slides-not-found](https://user-images.githubusercontent.com/64231691/194389436-14cbec79-2225-479c-a2eb-23fd7c9df389.png)

## update existing slides - admin user - before and after

![slides-before-update](https://user-images.githubusercontent.com/64231691/194388388-cb579841-0cc1-415a-ae48-8b2d2ee44e04.png)

![slide-admin-user-update](https://user-images.githubusercontent.com/64231691/194388453-b4a0c9c6-839b-4764-bcc8-73064390d58c.png)

## Comments

Como estoy un poco restrasado puse la lógica del _update_ directamente en el _service_, no sé si es del todo correcto ¿Debería usar un _mapper_?

2022-10-07 01:08 UTC, turcoamado requested changes
Me gusta que hayas probado tantos casos. Te respondí lo del mapper en el service, y otra cosa que modificaría sería el mensaje de error para el caso _update existing slides - regular user_, le pondría el mismo que el otro _Access denied_, total el Forbidden ya aparece en el tipo de error.

2022-10-07 01:08 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/SlidesServiceImpl.java
> +        Slides slidesToUpdate = (Slides) currentSlides.get();
Con respecto a tu consulta, sí, es preferible hacer esto a través de un mapper y no casteandolo, pero tampoco está mal, porque vos ya sabés que tipo de objeto es, el problema es en realidad si tenés diferentes atributos en uno y otro. Para respetar lo que venimos haciendo lo pasaría a un mapper, solo esta línea, pasarle el DTO y que me devuelva una entidad, claro que el id tiene que ser el mismo que el del DTO

2022-10-07 21:34 UTC, joeldevel commented
## update existing slides - regular user

![Screenshot 2022-10-07 at 18-32-30 Screenshot from 2022-10-07 18-26-12 png (PNG Image 1280 × 720 pixels)](https://user-images.githubusercontent.com/64231691/194660498-367b234f-f129-431f-835b-a7e9f0e3c42b.png)

2022-10-07 21:45 UTC, joeldevel commented
Para poder usar el mensaje de _access denied_ tuve que implementar dos clases que después se usan en _AppSecurity_ . Las puse en un nuevo paquete exception bajo security ya que no sé bien dónde irían.

2022-10-08 03:59 UTC, turcoamado approved these changes
Que buen trabajo Cris! Pensé que ya lo tenían implementado, por eso te lo mencioné, no me imaginé que debías hacer todo esto.
Quizás se podría haber puesto dentro del package exception, pero nada más. 
Buenísimo!

2022-10-08 20:26 UTC, merged