OT29880 feat: add endpoint comments by news id
alkemyTech/OT298-server pull request #71
Opened 2022-10-09 18:14 UTC by CarolinaCQ

![comments_by_new](https://user-images.githubusercontent.com/92055917/194772813-eb185890-b825-46bc-b9fd-0f2619e868a1.PNG)
![not_found_comments_by_new](https://user-images.githubusercontent.com/92055917/194772819-0af9fdff-b2ee-4955-be1d-94dff19f35b9.PNG)

2022-10-09 18:51 UTC, CarolinaCQ commented
@turcoamado hice un segundo commit con modificaciones respecto a la información que devuelve el endpoint sobre comments y la autorización, porque después de hacer el pr me di cuenta que lo pensé todo para admin y tenía que ser para user. Te dejo las nuevas capturas. Gracias
![not_found_comments_by_new](https://user-images.githubusercontent.com/92055917/194774418-3080d85e-e85f-4905-8d12-19ea6876cf94.PNG)
![comments_by_new](https://user-images.githubusercontent.com/92055917/194774416-ffee8494-9280-448a-a3f4-aa6f05e89d46.PNG)

2022-10-11 01:01 UTC, turcoamado requested changes
Está muy bueno Caro! Yo le modificaría el código de error nada más

2022-10-11 01:01 UTC, turcoamado commented on src/main/java/com/alkemy/ong/exception/ControllerExceptionHandler.java
> +                HttpStatus.OK.value(),
Yo le pondría un NO_CONTENT como código de error tal vez

2022-10-11 01:01 UTC, turcoamado commented on src/main/java/com/alkemy/ong/repository/NewsRepository.java
> +    @Query("SELECT c FROM News n JOIN n.comments c WHERE n.id = :id")
Está muy bien! Otra opción es realizar el filtrado desde el service con código Java, pero esto es totalmente válido e incluso podría llegar a ser más performante si tenemos gran volumen de registros

2022-10-11 01:01 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/CommentMapper.java
> +        for(Comment comment : comments){
Esto también podría haberse manejado mediante una expresión lambda

2022-10-11 20:54 UTC, CarolinaCQ commented on src/main/java/com/alkemy/ong/exception/ControllerExceptionHandler.java
> +                HttpStatus.OK.value(),
Dalee Turco lo modifico si

2022-10-11 21:14 UTC, turcoamado approved these changes

2022-10-11 21:14 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/CommentMapper.java
> +                comments.stream().map(comment -> commentBodyToCommentBasicDTO(comment)).collect(Collectors.toList());
Genial!

2022-10-11 21:28 UTC, merged