Testing ot298 91 user endpoints
alkemyTech/OT298-server pull request #78
Opened 2022-10-13 17:45 UTC by montexbjeliseo

**Summary**

- GET Test
    - Getting all users without authentication
    - Valid getting all users

- UPDATE Test
    - Valid update
    - Not found update

- DELETE Test
    - Not found delete
    - Valid delete
    - Not authorized delete

2022-10-14 21:11 UTC, turcoamado requested changes
Está muy bien! Te dejé una observación como mejora

2022-10-14 21:11 UTC, turcoamado commented on src/test/java/com/alkemy/ong/controller/UserControllerTests.java
> +    public List<AuxUserGetDto> generateUserList() {
Esto que hiciste acá está bien pensado pero se puede mejorar, bien pensado porque estas creando la lista cada vez que usas los test y luego según los datos que cargaste en la lista lo que buscas y testeas. Para eso se puede generar el método con la annotation @Before o alguna de esas según exactamente que se necesite. Te dejo un link que te explica algo más acá: https://www.baeldung.com/junit-before-beforeclass-beforeeach-beforeall

2022-10-14 23:57 UTC, montexbjeliseo commented on src/test/java/com/alkemy/ong/controller/UserControllerTests.java
> +    public List<AuxUserGetDto> generateUserList() {
Ahí le agregué @BeforeAll que es de JUnit 5

2022-10-17 16:05 UTC, turcoamado approved these changes
buenísimo! me gusta tmb el nombre setup() para indicar que son métodos de configuración

2022-10-18 20:34 UTC, merged