Feature/ot298 95 test activities endpoints
alkemyTech/OT298-server pull request #83
Opened 2022-10-17 01:00 UTC by joeldevel

## Some basic tests

![Screenshot from 2022-10-16 21-53-48](https://user-images.githubusercontent.com/64231691/196068170-ab07339e-fdce-4e6c-9751-c0fffa2e7036.png)

2022-10-17 16:20 UTC, turcoamado requested changes
Está muy bien tu PR, te marqué dos pavadas y te dejo algo más acá, para los nombres de los métodos seguite esto https://stackoverflow.com/questions/155436/unit-test-naming-best-practices

2022-10-17 16:20 UTC, turcoamado commented on src/test/java/com/alkemy/ong/controller/ActivityControllerTest.java
> +    ObjectMapper objectMapper = new ObjectMapper();
Estas dos hacelas privadas

2022-10-17 16:20 UTC, turcoamado commented on src/test/java/com/alkemy/ong/controller/ActivityControllerTest.java
> +        ActivityDTO activity = new ActivityDTO(1L,
Fijate que esto lo haces más de una vez, para performar mejor se puede sacar a un método como hacemos siempre y en testing podemos utilizar la annotation @Before o @BeforeAll para que lo que está bajo esa anotación se ejecute siempre antes de realizar un test. Entonces podrías identificar aquellos bloques de código que se repiten y abstraerlos en un método y luego llamar a esos métodos en otro que sea una especie de setUp o init

2022-10-18 13:25 UTC, joeldevel commented
## Resumen

- Con respecto a los nombres de los métodos creo que se ajustan a lo que se propone en el post de SO ya que describen la funcionalidad sin dar detalles de la implementación.

- Extraje unas funcionalidades que se repetían.

Cualquier sugerencia es bienvenida.

2022-10-19 19:30 UTC, turcoamado approved these changes
Bueno genial!!

2022-10-19 19:37 UTC, merged